import { useMemo, useState } from "react";
import { CheckCircle2, Database, Download, ExternalLink, LoaderCircle, MapPin } from "lucide-react";
import type { ViewProps } from "../App";
import type { AnitabiPreview } from "../types";
import { fetchAnitabi, openExternal } from "../lib/desktop";
import { chooseLegacyExport } from "../lib/legacy-file";
import { importAnitabiPreview, mergeLegacySnapshot } from "../lib/domain";
import { convertLegacyExport } from "../lib/legacy";

export function ImportView({ snapshot, update, navigate }: ViewProps) {
  const [subjectId, setSubjectId] = useState(""); const [preview, setPreview] = useState<AnitabiPreview | null>(null); const [selected, setSelected] = useState<Set<string>>(new Set()); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState("");
  const existing = useMemo(() => new Set(snapshot.spots.map((spot) => spot.anitabiPointId).filter(Boolean)), [snapshot.spots]);
  const search = async () => { const id = Number(subjectId); if (!Number.isInteger(id) || id <= 0) { setError("请输入有效的 Bangumi Subject ID"); return; } setLoading(true); setError(""); setResult(""); try { const data = await fetchAnitabi(id); setPreview(data); setSelected(new Set(data.points.map((point) => point.id))); } catch (e) { setError(e instanceof Error ? e.message : "无法连接 Anitabi"); } finally { setLoading(false); } };
  const commit = () => { if (!preview || !selected.size) return; const imported = importAnitabiPreview(snapshot, preview, selected); update(() => imported.snapshot); setResult(`导入完成：新增 ${imported.added} 个地点，更新 ${imported.updated} 个地点。`); };
  const importLegacy = async () => { setError(""); try { const raw = await chooseLegacyExport(); if (!raw) return; const converted = convertLegacyExport(raw); if (!confirm(`文件包含 ${converted.works.length} 部作品、${converted.spots.length} 个地点、${converted.visits.length} 条到访记录和 ${converted.photos.length} 张照片索引。确认合并吗？`)) return; update((current) => mergeLegacySnapshot(current, converted)); setResult("旧网站数据已合并。远程照片链接会保留，建议随后导出新的完整备份。"); } catch (e) { setError(e instanceof Error ? e.message : "旧数据导入失败"); } };
  return <div className="import-layout">
    <section className="panel import-card"><span className="eyebrow">ANITABI IMPORT</span><h2>从 Anitabi 带回巡礼地点</h2><p>输入 Bangumi 作品 ID，确认地点后写入本地数据库。个人笔记不会被刷新覆盖。</p><div className="subject-search"><input inputMode="numeric" value={subjectId} onChange={(e) => setSubjectId(e.target.value.replace(/\D/g, ""))} placeholder="例如：115908" /><button className="primary" onClick={() => void search()} disabled={loading}>{loading ? <LoaderCircle className="spin" size={17} /> : <Download size={17} />}读取作品</button></div>{error && <p className="inline-error">{error}</p>}{result && <p className="inline-success"><CheckCircle2 size={16} />{result}<button onClick={() => navigate("map")}>打开地图</button></p>}<div className="notice"><Database /><div><strong>数据使用说明</strong><p>仅调用公开 API，不抓取主站；截图使用 h360 预览，并保留来源署名和链接。</p></div></div></section>
    <section className="panel import-card"><span className="eyebrow">LEGACY MIGRATION</span><h2>导入旧网站数据</h2><p>支持旧网站设置页下载的 formatVersion 1 JSON。作品、地点、记录和照片索引会自动去重。</p><button className="secondary" onClick={() => void importLegacy()}><Database size={17} />选择旧网站 JSON</button></section>
    {preview && <section className="panel preview-card"><header>{preview.cover && <img src={preview.cover} alt="" />}<div><span className="eyebrow">IMPORT PREVIEW</span><h3>{preview.cn || preview.title}</h3><p>{preview.title}{preview.city ? ` · ${preview.city}` : ""}</p></div><button className="icon-button" onClick={() => void openExternal(`https://anitabi.cn/map?bangumiId=${preview.id}`)} title="在 Anitabi 查看"><ExternalLink /></button></header><div className="preview-tools"><label><input type="checkbox" checked={selected.size === preview.points.length} onChange={(e) => setSelected(e.target.checked ? new Set(preview.points.map((point) => point.id)) : new Set())} />选择全部</label><span>已选择 {selected.size}/{preview.points.length}</span></div><div className="point-list">{preview.points.map((point) => <label key={point.id} className={existing.has(point.id) ? "existing" : ""}><input type="checkbox" checked={selected.has(point.id)} onChange={(e) => setSelected((current) => { const next = new Set(current); if (e.target.checked) next.add(point.id); else next.delete(point.id); return next; })} />{point.image ? <img src={point.image} alt="" /> : <span className="point-icon"><MapPin /></span>}<div><strong>{point.name}</strong><span>{point.ep != null ? `第 ${point.ep} 集` : "集数未知"} · {point.geo[0].toFixed(4)}, {point.geo[1].toFixed(4)}</span>{point.origin && <small>来源：{point.origin}</small>}</div>{existing.has(point.id) && <b>将更新</b>}</label>)}</div><footer><span>数据来源 Anitabi · CC BY-NC-SA 4.0</span><button className="primary" disabled={!selected.size} onClick={commit}>导入 {selected.size} 个地点</button></footer></section>}
  </div>;
}
