import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Crosshair, ExternalLink, Filter, MapPin, Pencil, Plus, RotateCcw, Trash2, X } from "lucide-react";
import type { ViewProps } from "../App";
import type { Spot, SpotStatus } from "../types";
import { newId, nowIso } from "../types";
import { getGoogleApiKey, openExternal } from "../lib/desktop";
import { MapCanvas } from "../components/MapCanvas";
import type { Coordinate, MapViewState } from "../lib/map-adapter";
import { Modal } from "../components/Modal";

const statusLabel: Record<SpotStatus, string> = { unvisited: "未到访", planned: "计划中", visited: "已到访", skipped: "暂时跳过" };
const initialView: MapViewState = { center: { latitude: 36.2, longitude: 137.2 }, zoom: 4.25 };
const ANITABI_LICENSE_URL = "https://creativecommons.org/licenses/by-nc-sa/4.0/";

export function MapView({ snapshot, update }: ViewProps) {
  const [work, setWork] = useState("all"); const [city, setCity] = useState("all"); const [status, setStatus] = useState("all");
  const [selectedId, setSelectedId] = useState<string | null>(null); const [editing, setEditing] = useState<Spot | null | undefined>(undefined);
  const [picking, setPicking] = useState(false); const [view, setView] = useState(initialView); const [googleKey, setGoogleKeyState] = useState(""); const [mapError, setMapError] = useState("");
  useEffect(() => { void getGoogleApiKey().then(setGoogleKeyState); }, [snapshot.settings.mapProvider]);
  const cities = [...new Set(snapshot.spots.map((spot) => spot.city).filter(Boolean))] as string[];
  const filtered = useMemo(() => snapshot.spots.filter((spot) => (work === "all" || spot.workId === work) && (city === "all" || spot.city === city) && (status === "all" || spot.visitStatus === status)), [snapshot.spots, work, city, status]);
  const selected = snapshot.spots.find((spot) => spot.id === selectedId) ?? null;
  const selectedWork = snapshot.works.find((item) => item.id === selected?.workId);
  const save = (spot: Spot) => update((current) => ({ ...current, spots: current.spots.some((item) => item.id === spot.id) ? current.spots.map((item) => item.id === spot.id ? spot : item) : [spot, ...current.spots] }));
  const remove = (id: string) => { if (!confirm("确定删除这个地点及其到访记录和照片吗？")) return; update((current) => { const visits = current.visits.filter((item) => item.spotId !== id); return { ...current, spots: current.spots.filter((item) => item.id !== id), visits, photos: current.photos.filter((item) => item.spotId !== id) }; }); setSelectedId(null); };
  const pick = (coordinate: Coordinate) => { setPicking(false); setEditing({ id: newId(), workId: snapshot.works[0]?.id ?? "", name: "", latitude: coordinate.latitude, longitude: coordinate.longitude, visitStatus: "unvisited", createdAt: nowIso(), updatedAt: nowIso() }); };
  const provider = snapshot.settings.mapProvider === "google" && !googleKey ? "open" : snapshot.settings.mapProvider;
  return <div className="map-workspace">
    <div className="map-toolbar"><span><Filter size={16} />筛选</span><select value={work} onChange={(e) => setWork(e.target.value)}><option value="all">全部作品</option>{snapshot.works.map((item) => <option key={item.id} value={item.id}>{item.titleCn}</option>)}</select><select value={city} onChange={(e) => setCity(e.target.value)}><option value="all">全部城市</option>{cities.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">全部状态</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="ghost" onClick={() => { setWork("all"); setCity("all"); setStatus("all"); }}><RotateCcw size={15} />重置</button><span className="toolbar-spacer" /><button className={picking ? "primary" : "secondary"} onClick={() => setPicking(!picking)}><Crosshair size={16} />{picking ? "请点击地图" : "地图选点"}</button><button className="primary" onClick={() => setEditing(null)} disabled={!snapshot.works.length}><Plus size={16} />添加地点</button></div>
    <div className="map-stage"><MapCanvas provider={provider} tileUrl={snapshot.settings.mapStyleUrl} tileAttribution={snapshot.settings.mapAttribution ?? "© OpenStreetMap contributors"} tileAttributionUrl={snapshot.settings.mapAttributionUrl ?? "https://www.openstreetmap.org/copyright"} googleApiKey={googleKey} spots={filtered} selectedId={selectedId} picking={picking} view={view} onViewChange={setView} onSelect={setSelectedId} onPick={pick} onProviderError={(message) => { setMapError(message); if (snapshot.settings.mapProvider === "google") update((current) => ({ ...current, settings: { ...current.settings, mapProvider: "open" } })); }} />
      {snapshot.spots.length === 0 && <div className="map-empty"><MapPin /><strong>地图还是空的</strong><p>先添加作品，再标记第一个巡礼地点。</p></div>}
      {mapError && <div className="map-error">{mapError}<button onClick={() => setMapError("")}><X size={14} /></button></div>}
      {snapshot.settings.mapProvider === "google" && !googleKey && <div className="map-error">尚未配置 Google API Key，已使用开放地图。</div>}
      <aside className={`spot-drawer ${selected ? "open" : ""}`}>{selected && <><button className="drawer-close" onClick={() => setSelectedId(null)}><X size={18} /></button>{selected.referenceImageUrl && <img className="scene-image" src={selected.referenceImageUrl} alt="动画场景参考；版权归原权利人所有" />}<span className={`status-pill ${selected.visitStatus}`}>{statusLabel[selected.visitStatus]}</span><h2>{selected.name}</h2><p className="muted">{selectedWork?.titleCn}{selected.episode ? ` · 第 ${selected.episode} 集` : ""}</p><dl><div><dt>地区</dt><dd>{[selected.region, selected.city].filter(Boolean).join(" · ") || "未填写"}</dd></div><div><dt>坐标</dt><dd>{selected.latitude.toFixed(5)}, {selected.longitude.toFixed(5)}</dd></div><div><dt>到访次数</dt><dd>{snapshot.visits.filter((visit) => visit.spotId === selected.id).length}</dd></div></dl>{selected.sceneDescription && <blockquote>{selected.sceneDescription}</blockquote>}{selected.anitabiPointId && <p className="source-note">数据来源：Anitabi。参考图片版权归原权利人所有。{selected.referenceOrigin && <> 投稿来源：{selected.referenceOrigin}</>}{selected.referenceOriginUrl && <button title="打开原始来源" onClick={() => void openExternal(selected.referenceOriginUrl!)}><ExternalLink size={13} /></button>}<button title="查看 CC BY-NC-SA 4.0" onClick={() => void openExternal(ANITABI_LICENSE_URL)}>CC BY-NC-SA 4.0</button></p>}<div className="drawer-actions"><button className="primary" onClick={() => void openExternal(`https://www.google.com/maps/search/?api=1&query=${selected.latitude},${selected.longitude}`)}><ExternalLink size={15} />Google Maps</button><button className="secondary" onClick={() => setEditing(selected)}><Pencil size={15} />编辑</button><button className="danger-button" onClick={() => remove(selected.id)}><Trash2 size={15} /></button></div></>}
      </aside>
    </div><p className="attribution-note">{provider === "google" ? "Google Maps 及其内容适用 Google Maps Platform 条款" : (snapshot.settings.mapAttribution ?? "© OpenStreetMap contributors")} · Anitabi 地点数据遵循 CC BY-NC-SA 4.0</p>
    {editing !== undefined && <SpotForm spot={editing} works={snapshot.works} onClose={() => setEditing(undefined)} onSave={(spot) => { save(spot); setEditing(undefined); setSelectedId(spot.id); }} />}
  </div>;
}

function SpotForm({ spot, works, onClose, onSave }: { spot: Spot | null; works: ViewProps["snapshot"]["works"]; onClose: () => void; onSave: (spot: Spot) => void }) {
  const [form, setForm] = useState<Spot>(() => spot ?? { id: newId(), workId: works[0]?.id ?? "", name: "", latitude: 35.681236, longitude: 139.767125, visitStatus: "unvisited", createdAt: nowIso(), updatedAt: nowIso() });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.workId || !form.name.trim() || form.latitude < -90 || form.latitude > 90 || form.longitude < -180 || form.longitude > 180) return; onSave({ ...form, name: form.name.trim(), updatedAt: nowIso() }); };
  return <Modal title={spot?.name ? "编辑地点" : "添加地点"} onClose={onClose} wide><form className="form-grid" onSubmit={submit}><label>所属作品<select required value={form.workId} onChange={(e) => setForm({ ...form, workId: e.target.value })}>{works.map((work) => <option key={work.id} value={work.id}>{work.titleCn}</option>)}</select></label><label>到访状态<select value={form.visitStatus} onChange={(e) => setForm({ ...form, visitStatus: e.target.value as SpotStatus })}>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="full">地点名称<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>纬度<input required type="number" step="any" min="-90" max="90" value={form.latitude} onChange={(e) => setForm({ ...form, latitude: Number(e.target.value) })} /></label><label>经度<input required type="number" step="any" min="-180" max="180" value={form.longitude} onChange={(e) => setForm({ ...form, longitude: Number(e.target.value) })} /></label><label>城市<input value={form.city ?? ""} onChange={(e) => setForm({ ...form, city: e.target.value })} /></label><label>地址<input value={form.address ?? ""} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label><label>动画集数<input value={form.episode ?? ""} onChange={(e) => setForm({ ...form, episode: e.target.value })} /></label><label>画面时间点<input placeholder="04:42" value={form.sceneTimestamp ?? ""} onChange={(e) => setForm({ ...form, sceneTimestamp: e.target.value })} /></label><label className="full">参考截图 URL<input type="url" value={form.referenceImageUrl ?? ""} onChange={(e) => setForm({ ...form, referenceImageUrl: e.target.value })} /></label><label className="full">场景与交通笔记<textarea value={form.sceneDescription ?? ""} onChange={(e) => setForm({ ...form, sceneDescription: e.target.value })} /></label><footer className="form-actions full"><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary">保存地点</button></footer></form></Modal>;
}
