import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, DatabaseBackup, ExternalLink, Eye, EyeOff, FileText, KeyRound, Map, Palette, RotateCcw, Save } from "lucide-react";
import type { ViewProps } from "../App";
import type { AppSnapshot, MapProvider } from "../types";
import { exportBackup, getGoogleApiKey, openExternal, restoreBackup, setGoogleApiKey } from "../lib/desktop";

export function SettingsView({ snapshot, update, onReload }: ViewProps & { onReload: (snapshot: AppSnapshot) => void }) {
  const [key, setKey] = useState(""); const [showKey, setShowKey] = useState(false); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void getGoogleApiKey().then(setKey); }, []);
  const saveKey = async () => { setBusy(true); try { await setGoogleApiKey(key.trim()); setMessage(key.trim() ? "Google API Key 已保存到系统凭据管理器。" : "Google API Key 已移除。"); } finally { setBusy(false); } };
  const backup = async () => { setBusy(true); setMessage(""); try { const path = await exportBackup(password); if (path) setMessage(`备份已保存：${path}`); } catch (e) { setMessage(e instanceof Error ? e.message : "备份失败"); } finally { setBusy(false); } };
  const restore = async () => { if (!confirm("恢复前会自动保存当前数据。确定选择备份文件吗？")) return; setBusy(true); setMessage(""); try { const next = await restoreBackup(password); if (next) { onReload(next); setMessage("备份恢复完成。"); } } catch (e) { setMessage(e instanceof Error ? e.message : "恢复失败"); } finally { setBusy(false); } };
  const setProvider = (mapProvider: MapProvider) => update((current) => ({ ...current, settings: { ...current.settings, mapProvider } }));
  const resetOpenMap = () => update((current) => ({ ...current, settings: { ...current.settings, mapStyleUrl: "https://tile.openstreetmap.org/{z}/{x}/{y}.png", mapAttribution: "© OpenStreetMap contributors", mapAttributionUrl: "https://www.openstreetmap.org/copyright" } }));
  return <div className="settings-layout">
    <section className="panel setting-section"><header><Map /><div><h2>地图提供商</h2><p>开放地图无需密钥；Google 地图是可选增强模式。</p></div></header><div className="provider-grid"><button className={snapshot.settings.mapProvider === "open" ? "selected" : ""} onClick={() => setProvider("open")}><strong>开放地图</strong><span>MapLibre · OpenStreetMap</span><b>默认推荐</b></button><button className={snapshot.settings.mapProvider === "google" ? "selected" : ""} onClick={() => setProvider("google")}><strong>Google Maps</strong><span>需要自己的 API Key 与结算账号</span><b>可选</b></button></div><label className="stacked">开放地图瓦片地址<input value={snapshot.settings.mapStyleUrl} onChange={(e) => update((current) => ({ ...current, settings: { ...current.settings, mapStyleUrl: e.target.value } }))} /></label><label className="stacked">地图署名<input required value={snapshot.settings.mapAttribution ?? "© OpenStreetMap contributors"} onChange={(e) => update((current) => ({ ...current, settings: { ...current.settings, mapAttribution: e.target.value } }))} /><small>使用自定义瓦片时，必须按提供商要求填写并持续显示署名。</small></label><label className="stacked">署名或许可链接<input type="url" value={snapshot.settings.mapAttributionUrl ?? "https://www.openstreetmap.org/copyright"} onChange={(e) => update((current) => ({ ...current, settings: { ...current.settings, mapAttributionUrl: e.target.value } }))} /></label><div className="warning-note"><AlertTriangle /><p>OpenStreetMap 公共瓦片不允许批量下载或离线预取。更换瓦片地址前，请确认使用许可、限额和署名要求。</p></div><button className="text-button" onClick={resetOpenMap}><RotateCcw size={14} />恢复 OpenStreetMap 默认设置</button></section>
    <section className="panel setting-section"><header><KeyRound /><div><h2>Google Maps API Key</h2><p>Key 不进入数据库、日志或备份，只保存在 Windows 凭据管理器。</p></div></header><div className="secret-field"><input type={showKey ? "text" : "password"} value={key} onChange={(e) => setKey(e.target.value)} placeholder="AIza…" /><button className="icon-button" onClick={() => setShowKey(!showKey)}>{showKey ? <EyeOff /> : <Eye />}</button><button className="primary" onClick={() => void saveKey()} disabled={busy}><Save size={16} />保存</button></div><div className="warning-note"><AlertTriangle /><p>桌面 WebView 中的 Key 仍可能被本机用户提取。请仅允许 Maps JavaScript API，并在 Google Cloud 设置较低的每日配额。</p></div><button className="text-button" onClick={() => void openExternal("https://console.cloud.google.com/google/maps-apis/credentials")}><ExternalLink size={14} />打开 Google Cloud 凭据页面</button></section>
    <section className="panel setting-section"><header><DatabaseBackup /><div><h2>本地备份与恢复</h2><p>备份包含作品、地点、到访记录和本地照片，不包含 Google Key。</p></div></header><label className="stacked">备份密码（可选）<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="留空则生成普通备份" /><small>忘记密码将无法恢复加密备份。</small></label><div className="button-row"><button className="primary" onClick={() => void backup()} disabled={busy}><DatabaseBackup size={16} />导出完整备份</button><button className="secondary" onClick={() => void restore()} disabled={busy}><RotateCcw size={16} />从备份恢复</button></div></section>
    <section className="panel setting-section"><header><Palette /><div><h2>外观</h2><p>选择适合记录和整理照片的阅读方式。</p></div></header><div className="inline-fields"><label>主题<select value={snapshot.settings.theme} onChange={(e) => update((current) => ({ ...current, settings: { ...current.settings, theme: e.target.value as AppSnapshot["settings"]["theme"] } }))}><option value="light">浅色</option><option value="dark">深色</option><option value="system">跟随系统</option></select></label><label className="checkbox-label"><input type="checkbox" checked={snapshot.settings.compactNavigation} onChange={(e) => update((current) => ({ ...current, settings: { ...current.settings, compactNavigation: e.target.checked } }))} />使用紧凑导航栏</label></div></section>
    <section className="panel setting-section"><header><FileText /><div><h2>条款、隐私与许可</h2><p>查看项目公开条款、第三方来源和权利人联系渠道。</p></div></header><div className="button-row"><button className="secondary" onClick={() => void openExternal("https://github.com/kumiko399/junrei-journal/blob/main/TERMS.md")}><ExternalLink size={15} />使用条款</button><button className="secondary" onClick={() => void openExternal("https://github.com/kumiko399/junrei-journal/blob/main/PRIVACY.md")}><ExternalLink size={15} />隐私说明</button><button className="secondary" onClick={() => void openExternal("https://github.com/kumiko399/junrei-journal/blob/main/THIRD_PARTY_NOTICES.md")}><ExternalLink size={15} />第三方许可</button><button className="text-button" onClick={() => void openExternal("https://github.com/kumiko399/junrei-journal/issues")}><ExternalLink size={14} />权利问题与移除请求</button></div></section>
    {message && <div className="settings-message"><CheckCircle2 />{message}</div>}
  </div>;
}
