import { useState, type FormEvent } from "react";
import { CalendarDays, MapPin, Plus, Star, Trash2 } from "lucide-react";
import type { ViewProps } from "../App";
import type { Visit } from "../types";
import { newId, nowIso } from "../types";
import { Modal } from "../components/Modal";

export function VisitsView({ snapshot, update }: ViewProps) {
  const [editing, setEditing] = useState<Visit | null | undefined>(undefined);
  const visits = [...snapshot.visits].sort((a, b) => b.visitedAt.localeCompare(a.visitedAt));
  const save = (visit: Visit) => update((current) => ({ ...current, visits: current.visits.some((item) => item.id === visit.id) ? current.visits.map((item) => item.id === visit.id ? visit : item) : [visit, ...current.visits], spots: current.spots.map((spot) => spot.id === visit.spotId ? { ...spot, visitStatus: "visited", updatedAt: nowIso() } : spot) }));
  const remove = (id: string) => { if (!confirm("确定删除这条到访记录吗？照片记录会保留但解除关联。")) return; update((current) => ({ ...current, visits: current.visits.filter((item) => item.id !== id), photos: current.photos.map((photo) => photo.visitId === id ? { ...photo, visitId: null } : photo) })); };
  return <><div className="toolbar"><div className="toolbar-copy"><span className="eyebrow">VISIT JOURNAL</span><p>记录每一次真正抵达场景的日子。</p></div><button className="primary" onClick={() => setEditing(null)} disabled={!snapshot.spots.length}><Plus size={17} />新增到访</button></div>
    {visits.length === 0 ? <div className="panel empty-state tall"><CalendarDays /><strong>还没有巡礼日记</strong><p>先在地图中添加地点，再记录第一次到访。</p></div> : <div className="visit-list">{visits.map((visit) => { const spot = snapshot.spots.find((item) => item.id === visit.spotId); const work = snapshot.works.find((item) => item.id === spot?.workId); return <article key={visit.id} className="visit-card" onClick={() => setEditing(visit)}><time><strong>{visit.visitedAt.slice(8, 10)}</strong><span>{visit.visitedAt.slice(0, 7)}</span></time><div className="visit-main"><span className="eyebrow">{work?.titleCn ?? "未知作品"}</span><h3>{spot?.name ?? "未知地点"}</h3><p>{visit.note || "这一天还没有留下文字。"}</p><div className="visit-tags"><span><MapPin size={13} />{spot?.city || "未填写城市"}</span>{visit.weather && <span>{visit.weather}</span>}{visit.companions && <span>同行：{visit.companions}</span>}</div></div><div className="visit-rating">{visit.rating ? <><Star size={17} fill="currentColor" />{visit.rating}</> : "—"}<button className="danger" onClick={(e) => { e.stopPropagation(); remove(visit.id); }}><Trash2 size={16} /></button></div></article>; })}</div>}
    {editing !== undefined && <VisitForm visit={editing} spots={snapshot.spots} onClose={() => setEditing(undefined)} onSave={(visit) => { save(visit); setEditing(undefined); }} />}
  </>;
}

function VisitForm({ visit, spots, onClose, onSave }: { visit: Visit | null; spots: ViewProps["snapshot"]["spots"]; onClose: () => void; onSave: (visit: Visit) => void }) {
  const [form, setForm] = useState<Visit>(() => visit ?? { id: newId(), spotId: spots[0]?.id ?? "", visitedAt: new Date().toISOString().slice(0, 10), visitedTime: "", note: "", weather: "", companions: "", rating: null, matchedAngle: false, createdAt: nowIso(), updatedAt: nowIso() });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.spotId || !form.visitedAt) return; onSave({ ...form, updatedAt: nowIso() }); };
  return <Modal title={visit ? "编辑到访记录" : "新增到访记录"} onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="full">巡礼地点<select value={form.spotId} onChange={(e) => setForm({ ...form, spotId: e.target.value })}>{spots.map((spot) => <option key={spot.id} value={spot.id}>{spot.name}</option>)}</select></label><label>到访日期<input type="date" required value={form.visitedAt} onChange={(e) => setForm({ ...form, visitedAt: e.target.value })} /></label><label>时间<input type="time" value={form.visitedTime ?? ""} onChange={(e) => setForm({ ...form, visitedTime: e.target.value })} /></label><label>天气<input placeholder="晴 / 雨 / 多云" value={form.weather ?? ""} onChange={(e) => setForm({ ...form, weather: e.target.value })} /></label><label>同行者<input value={form.companions ?? ""} onChange={(e) => setForm({ ...form, companions: e.target.value })} /></label><label>评分<select value={form.rating ?? ""} onChange={(e) => setForm({ ...form, rating: e.target.value ? Number(e.target.value) : null })}><option value="">暂不评分</option>{[1,2,3,4,5].map((n) => <option key={n} value={n}>{n} 星</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={form.matchedAngle} onChange={(e) => setForm({ ...form, matchedAngle: e.target.checked })} />成功还原动画构图</label><label className="full">巡礼笔记<textarea rows={5} value={form.note ?? ""} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><footer className="form-actions full"><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary">保存记录</button></footer></form></Modal>;
}
