import { useMemo, useState, type FormEvent } from "react";
import { BookOpen, MapPin, Pencil, Plus, Search, Trash2 } from "lucide-react";
import type { ViewProps } from "../App";
import type { AnimeWork, WorkStatus } from "../types";
import { newId, nowIso } from "../types";
import { Modal } from "../components/Modal";

const labels: Record<WorkStatus, string> = { not_started: "想去巡礼", in_progress: "巡礼中", completed: "已完成", archived: "已归档" };

export function WorksView({ snapshot, update, navigate }: ViewProps) {
  const [query, setQuery] = useState(""); const [editing, setEditing] = useState<AnimeWork | null | undefined>(undefined);
  const works = useMemo(() => snapshot.works.filter((work) => `${work.titleCn} ${work.titleOriginal ?? ""} ${work.city ?? ""}`.toLowerCase().includes(query.toLowerCase())), [snapshot.works, query]);
  const save = (work: AnimeWork) => update((current) => ({ ...current, works: current.works.some((item) => item.id === work.id) ? current.works.map((item) => item.id === work.id ? work : item) : [work, ...current.works] }));
  const remove = (id: string) => { if (!confirm("删除作品会一并删除其地点、记录和照片，确定继续吗？")) return; update((current) => { const spotIds = new Set(current.spots.filter((spot) => spot.workId === id).map((spot) => spot.id)); const visitIds = new Set(current.visits.filter((visit) => spotIds.has(visit.spotId)).map((visit) => visit.id)); return { ...current, works: current.works.filter((work) => work.id !== id), spots: current.spots.filter((spot) => !spotIds.has(spot.id)), visits: current.visits.filter((visit) => !spotIds.has(visit.spotId)), photos: current.photos.filter((photo) => !spotIds.has(photo.spotId) && (!photo.visitId || !visitIds.has(photo.visitId))) }; }); };
  return <>
    <div className="toolbar"><label className="search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索作品、城市…" /></label><button className="primary" onClick={() => setEditing(null)}><Plus size={17} />添加作品</button></div>
    {works.length === 0 ? <div className="panel empty-state tall"><BookOpen /><strong>{snapshot.works.length ? "没有匹配的作品" : "作品库还是空的"}</strong><p>手动添加，或前往“数据导入”通过 Bangumi ID 导入。</p><button className="secondary" onClick={() => navigate("import")}>前往导入</button></div> : <div className="work-grid">{works.map((work) => { const spots = snapshot.spots.filter((spot) => spot.workId === work.id); const visited = spots.filter((spot) => spot.visitStatus === "visited").length; return <article className="work-card" key={work.id}>{work.coverUrl ? <img src={work.coverUrl} alt="" /> : <div className="cover-placeholder"><BookOpen /></div>}<div className="work-card-body"><span className={`status-pill ${work.status}`}>{labels[work.status]}</span><h3>{work.titleCn}</h3><p>{work.titleOriginal || "未填写原名"}</p><div className="work-meta"><span><MapPin size={14} />{work.city || "未填写城市"}</span><b>{visited}/{spots.length}</b></div><div className="progress-line"><i style={{ width: `${spots.length ? visited / spots.length * 100 : 0}%` }} /></div><div className="card-actions"><button onClick={() => setEditing(work)}><Pencil size={15} />编辑</button><button className="danger" onClick={() => remove(work.id)}><Trash2 size={15} />删除</button></div></div></article>; })}</div>}
    {editing !== undefined && <WorkForm work={editing} onClose={() => setEditing(undefined)} onSave={(work) => { save(work); setEditing(undefined); }} />}
  </>;
}

function WorkForm({ work, onClose, onSave }: { work: AnimeWork | null; onClose: () => void; onSave: (work: AnimeWork) => void }) {
  const [form, setForm] = useState(() => work ?? { id: newId(), titleCn: "", titleOriginal: "", coverUrl: "", city: "", status: "not_started" as WorkStatus, description: "", personalNote: "", createdAt: nowIso(), updatedAt: nowIso() });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.titleCn.trim()) return; onSave({ ...form, titleCn: form.titleCn.trim(), updatedAt: nowIso() }); };
  return <Modal title={work ? "编辑作品" : "添加作品"} onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="full">中文标题<input required value={form.titleCn} onChange={(e) => setForm({ ...form, titleCn: e.target.value })} /></label><label>原始标题<input value={form.titleOriginal ?? ""} onChange={(e) => setForm({ ...form, titleOriginal: e.target.value })} /></label><label>主要城市<input value={form.city ?? ""} onChange={(e) => setForm({ ...form, city: e.target.value })} /></label><label className="full">封面 URL<input type="url" value={form.coverUrl ?? ""} onChange={(e) => setForm({ ...form, coverUrl: e.target.value })} /></label><label>收藏状态<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as WorkStatus })}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>发行年份<input type="number" min="1900" max="2100" value={form.releaseYear ?? ""} onChange={(e) => setForm({ ...form, releaseYear: e.target.value ? Number(e.target.value) : null })} /></label><label className="full">作品简介<textarea value={form.description ?? ""} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label className="full">个人笔记<textarea value={form.personalNote ?? ""} onChange={(e) => setForm({ ...form, personalNote: e.target.value })} /></label><footer className="form-actions full"><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary" type="submit">保存作品</button></footer></form></Modal>;
}
